### ISSUE TITLE
Uploading from iOS

### ISSUE THREAD

**Issue by sweetcoco** [Constantine-Fry/rebekka#1]
The upload method takes a url, which makes sense in the example in your readme. However, is this possible to do from the camera roll on an iOS device?

**Comment by constantine-fry** [comment]
Yes, you get image file from camera roll, save it on disk, upload it to FTP server and remove file.

**Comment by sweetcoco** [comment]
Ah! Thanks for the quick response, and the framework!

**Comment by juanjoserodrigolazaro** [comment]
@sweetcoco could you make it?
