### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by peporroncin** [Constantine-Fry/rebekka#12]
Hello to everybody! I'm totally new with IOs and Swift.

I need an app to connect to ftp address in a specific folder (always the same). I've seen rebekka project but I've been having problems to use it. Please, could you help me to begin with the project? I've read the tutorial in  _https://github.com/Constantine-Fry/rebekka_ but I've got problems in first step using git.

I need a tutorial for dummies :D 

How can I merge rebekka project with a new swift project? 

Thank you in advance!!!

**Comment by cwstrmnn** [comment]
Same problem!

**Comment by lakhanmankani** [comment]
Try this `git submodule add github.com:Constantine-Fry/rebekka.git`.

**Comment by constantine-fry** [comment]
I believe I can this issue. It has nothing to do with this project. You can learn git command line tool https://git-scm.com/book/en/v2 or use github client, sourcetree or tower.
