### ISSUE TITLE
FTPS Connection

### ISSUE THREAD

**Issue by Chefda** [Constantine-Fry/rebekka#2]
I can not login ftps (ftp with ssl) server. How can i make TLS acceptence?

**Comment by shorabhd** [comment]
I think even I am facing the same issue. I am getting this error,

nil, error: Optional(Error Domain=kCFErrorDomainCFNetwork Code=200 "(null)" UserInfo={kCFFTPStatusCodeKey=534})

Can you please suggest on how to deal with this?

**Comment by pradeep7may** [comment]
Upload not working in Xcode8. Could you please fix that?

**Comment by juanjoserodrigolazaro** [comment]
could you fix it? i have the same problem @shorabhd @pradeep7may @Chefda

**Comment by shorabhd** [comment]
Hi,

It doesn't work for FTPS.

Regards,
Shorabh Dhandharia
