### ISSUE TITLE
CFFTP Functions are depreciated

### ISSUE THREAD

**Issue by srolesen** [Constantine-Fry/rebekka#4]
apple (sadly) doesn't like FTP any more and CFFTP functions are depreciated with IOS 9, what can be done ????
https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFFTPStreamRef/

**Comment by constantine-fry** [comment]
Did you try NSURLSession?

**Comment by srolesen** [comment]
thank you for taking the time to reply,  i'm not skilled enough to write a library like you (I wish) but i thought NSURLSession only supports downloads.

**Comment by constantine-fry** [comment]
I have never tried to NSURLSession with ftp servers, but in general it supports uploading.

**Comment by srolesen** [comment]
sounds like good news to me :)
I have to say i'm already feeling i'm in over my head just trying to use your library, but if you could use help to update it from depreciated methods I will definitely help in what way I can!

**Comment by constantine-fry** [comment]
I will try to update my library as soon as I find time.

**Comment by srolesen** [comment]
Thank you :+1:
