### ISSUE TITLE
Feature Request: Deletion

### ISSUE THREAD

**Issue by jshaw1109** [Constantine-Fry/rebekka#7]
Is there an API to delete remote directory/file?

**Comment by srolesen** [comment]
yeah create and delete is in there

**Comment by jshaw1109** [comment]
What's the API call to delete a remote file? I don't see them in there. Btw, thx for the nice and simple API

I've been looking I see the 4 public methods:

public func list(path: String, completionHandler: ResourceResultCompletionHandler)
public func createDirectory(path: String, completionHandler: BooleanResultCompletionHandler)
public func download(path: String, completionHandler: FileURLResultCompletionHandler)
public func upload(fileURL: NSURL, path: String, completionHandler: BooleanResultCompletionHandler)

**Comment by constantine-fry** [comment]
I'm sorry. This library uses CFFTPStream which has no support for FTP deletion commands.

**Comment by asifbilal786** [comment]
I think @jshaw1109 is right. There should be a FTP delete method otherwise this control is incomplete. @Constantine-Fry , you should find a way to add the deletion functionality to make it complete.
